@startwbs
'https://plantuml.com/wbs-diagram

* Jucudent

** 生徒管理
*** 生徒一覧
*** 生徒詳細
**** 支払者情報

** 授業管理
*** 本日の授業
*** 授業一覧

** 用具管理
*** 書籍管理

** 成績管理
*** 成績一覧

** 講師管理
*** 権限管理

** 会社管理
*** 教室管理

** ダッシュボード
*** 今日の授業
*** 今日の講師
*** 欠席者

** 管理者ページ
*** メンバーの招待
*** ログアウト
@endwbs